"""
Script Writer Agent using OpenAI Agents SDK.

Specialized agent for generating and modifying Blender 5.0 Mantaflow
Python scripts for VFX effects.

Key capabilities:
- Script generation with UCB1 technique selection
- Script modification based on quality feedback
- Parameter validation against Blender API ranges
- Integration with script-generator MCP server
"""

from __future__ import annotations

import os
from typing import Optional, TYPE_CHECKING

from agents import Agent, ModelSettings

if TYPE_CHECKING:
    from tools.script_generator_tools import (
        generate_script,
        modify_script,
        validate_script,
        list_techniques,
        recommend_technique,
        record_technique_outcome,
    )

# Import tools at runtime to avoid circular imports
from tools.script_generator_tools import (
    generate_script,
    modify_script,
    validate_script,
    list_techniques,
    recommend_technique,
    record_technique_outcome,
)

# Blender 5.0 API parameter ranges (MUST be enforced during script generation)
# Source: bpy.types.FluidDomainSettings, bpy.types.FluidFlowSettings
BLENDER_PARAMETER_RANGES = """
PARAMETER RANGES (STRICTLY ENFORCED - values outside ranges will cause validation failures):
- vorticity: 0.0-4.0 (controls rotational flow - from bpy.types.FluidDomainSettings)
- flame_vorticity: 0.0-2.0 (flame-specific vorticity - from bpy.types.FluidDomainSettings)
- flame_smoke: 0.0-8.0 (smoke generated by flames)
- burning_rate: 0.01-4.0 (fuel consumption speed)
- flame_max_temp: 1.0-10.0 (max flame temperature multiplier)
- flame_ignition: 0.5-5.0 (ignition temperature)
- domain_resolution: 32-512 (simulation detail level, resolution_max)
- alpha: -5.0 to 5.0 (buoyancy heat)
- beta: -5.0 to 5.0 (buoyancy density)
- dissolve_speed: 1-10000 (smoke dissolve speed)
- noise_strength: 0.0-10.0 (upres noise strength)
- temperature: -10.0-10.0 (flow temperature, not Kelvin!)
- fuel_amount: 0.0-10.0 (fuel emission amount)
- velocity_normal: -100.0 to 100.0 (emission velocity along normal)
- velocity_random: 0.0-10.0 (random velocity component)

IMPORTANT: These ranges come directly from Blender 5.0 Python API documentation.
Clamp ALL parameters to their valid ranges before generating scripts.
"""

# Agent instructions for script generation
SCRIPT_WRITER_INSTRUCTIONS = f"""You generate Blender 5.0 Mantaflow Python scripts for VFX effects.

Your role:
1. Generate new scripts using UCB1 technique selection for variety
2. Modify existing scripts based on quality feedback
3. Validate all scripts before returning
4. Apply parameter ranges from Blender API

CRITICAL PATH HANDLING:
- ALWAYS use the EXACT paths returned from tool responses
- NEVER invent, guess, or modify paths (no "/mnt/data/", no path prefixes)
- When generate_script() returns script_path="assets/blender_scripts/generated/foo.py",
  use EXACTLY "assets/blender_scripts/generated/foo.py" for validate_script()
- Parse tool response JSON and extract the exact script_path value

WORKFLOW:
1. For NEW scripts:
   a. ALWAYS call recommend_technique() first for technique selection
   b. Use the recommended technique in generate_script()
   c. Extract the EXACT script_path from generate_script() response JSON
   d. Call validate_script() with that EXACT path (no modifications)
   e. Return the script path and any validation warnings

2. For MODIFICATIONS:
   a. Read the current issues from the evaluation
   b. Determine which parameters to adjust
   c. Call modify_script() with the changes
   d. Extract the EXACT script_path from modify_script() response JSON
   e. Call validate_script() with that EXACT path

{BLENDER_PARAMETER_RANGES}

COMMON FIXES:
- "TOO DARK" → Increase emission_intensity, flame_max_temp
- "LACKS STRUCTURE" → Increase turbulence, vorticity
- "TOO BRIGHT" → Decrease emission_intensity
- "WRONG COLOR" → Adjust flame_max_temp (higher = bluer, lower = redder)
- "CLIPPING AT EDGES" → Increase domain_scale, adjust emitter position
- "NOT ENOUGH SMOKE" → Increase flame_smoke, smoke_density

OUTPUT FORMAT:
Always return JSON with:
- script_path: Path to generated/modified script
- technique_used: Name of technique (if new script)
- parameters: Dict of key parameters used
- validation: Results from validate_script()
- warnings: Any issues found during validation
"""


class ScriptWriterAgent:
    """
    Script Writer Agent for Blender 5.0 VFX script generation.

    Uses gpt-5.2 with high reasoning effort for intelligent script generation
    with UCB1-based technique selection for exploration/exploitation balance.
    """

    def __init__(self, model: str = "gpt-5.2"):
        """
        Initialize the script writer agent.

        Args:
            model: OpenAI model to use (default: gpt-5.2 for intelligent code generation)
        """
        self.model = os.getenv("SCRIPT_WRITER_MODEL", model)
        self._agent: Optional[Agent] = None

    def initialize(self, custom_instructions: str = "") -> None:
        """
        Initialize the agent with tools.

        Args:
            custom_instructions: Additional context (e.g., current session state)
        """
        instructions = SCRIPT_WRITER_INSTRUCTIONS
        if custom_instructions:
            instructions = instructions + "\n\n" + custom_instructions

        self._agent = Agent(
            name="Script Writer",
            instructions=instructions,
            model=self.model,
            model_settings=ModelSettings(
                reasoning={
                    "effort": "high"  # High reasoning for complex code generation
                },
                # Note: temperature not supported with gpt-5.2 reasoning models
            ),
            tools=[
                generate_script,
                modify_script,
                validate_script,
                list_techniques,
                recommend_technique,
                record_technique_outcome,
            ],
        )

    @property
    def agent(self) -> Agent:
        """Get the underlying Agent instance for handoffs."""
        if not self._agent:
            raise RuntimeError("ScriptWriterAgent not initialized. Call initialize() first.")
        return self._agent


def create_script_writer(custom_instructions: str = "") -> Agent:
    """
    Factory function to create and initialize a script writer agent.

    Args:
        custom_instructions: Additional context to append

    Returns:
        Initialized Agent instance ready for use
    """
    writer = ScriptWriterAgent()
    writer.initialize(custom_instructions=custom_instructions)
    return writer.agent


# Convenience alias matching the agents/__init__.py export
ScriptWriterAgent = ScriptWriterAgent


# For testing
if __name__ == "__main__":
    import asyncio
    from agents import Runner

    async def test():
        print("Testing ScriptWriterAgent...")
        print("-" * 60)

        agent = create_script_writer()

        # Test script generation
        result = await Runner.run(
            agent,
            "Generate a Blender script for a rising mushroom cloud explosion with bright orange flames"
        )

        print(f"Response: {result.final_output}")

    asyncio.run(test())
