"""
Script Writer Agent using OpenAI Agents SDK.

Specialized agent for generating and modifying Blender 5.0 Mantaflow
Python scripts for VFX effects.

Key capabilities:
- Script generation with UCB1 technique selection
- Script modification based on quality feedback
- Parameter validation against Blender API ranges
- Integration with script-generator MCP server
"""

from __future__ import annotations

import os
from typing import Optional, TYPE_CHECKING

from agents import Agent, ModelSettings

if TYPE_CHECKING:
    from tools.script_generator_tools import (
        generate_script,
        modify_script,
        validate_script,
        list_techniques,
        recommend_technique,
        record_technique_outcome,
    )

# Import tools at runtime to avoid circular imports
from tools.script_generator_tools import (
    generate_script,
    modify_script,
    validate_script,
    list_techniques,
    recommend_technique,
    record_technique_outcome,
)

# Blender 5.0 API parameter ranges (enforced during script generation)
BLENDER_PARAMETER_RANGES = """
PARAMETER RANGES (enforced):
- turbulence: 0.0-1.0 (controls fluid swirling motion)
- vorticity: 0.0-1.0 (controls rotational flow)
- flame_smoke: 0.0-8.0 (smoke generated by flames)
- burning_rate: 0.01-4.0 (fuel consumption speed)
- domain_resolution: 32-512 (simulation detail level)
- timesteps_max: 1-45 (simulation stability)
- cfl_condition: 0.0-10.0 (Courant-Friedrichs-Lewy stability)
- temperature: 0-100000K (emission temperature)
- emission_intensity: 0.0-100.0 (light emission strength)
- smoke_density: 0.0-1.0 (smoke opacity)
"""

# Agent instructions for script generation
SCRIPT_WRITER_INSTRUCTIONS = f"""You generate Blender 5.0 Mantaflow Python scripts for VFX effects.

Your role:
1. Generate new scripts using UCB1 technique selection for variety
2. Modify existing scripts based on quality feedback
3. Validate all scripts before returning
4. Apply parameter ranges from Blender API

WORKFLOW:
1. For NEW scripts:
   a. ALWAYS call recommend_technique() first for technique selection
   b. Use the recommended technique in generate_script()
   c. Call validate_script() to check the result
   d. Return the script path and any validation warnings

2. For MODIFICATIONS:
   a. Read the current issues from the evaluation
   b. Determine which parameters to adjust
   c. Call modify_script() with the changes
   d. Validate the modified script

{BLENDER_PARAMETER_RANGES}

COMMON FIXES:
- "TOO DARK" → Increase emission_intensity, flame_max_temp
- "LACKS STRUCTURE" → Increase turbulence, vorticity
- "TOO BRIGHT" → Decrease emission_intensity
- "WRONG COLOR" → Adjust flame_max_temp (higher = bluer, lower = redder)
- "CLIPPING AT EDGES" → Increase domain_scale, adjust emitter position
- "NOT ENOUGH SMOKE" → Increase flame_smoke, smoke_density

OUTPUT FORMAT:
Always return JSON with:
- script_path: Path to generated/modified script
- technique_used: Name of technique (if new script)
- parameters: Dict of key parameters used
- validation: Results from validate_script()
- warnings: Any issues found during validation
"""


class ScriptWriterAgent:
    """
    Script Writer Agent for Blender 5.0 VFX script generation.

    Uses gpt-4.1-mini for fast, cost-effective script generation
    with UCB1-based technique selection for exploration/exploitation balance.
    """

    def __init__(self, model: str = "gpt-4.1-mini"):
        """
        Initialize the script writer agent.

        Args:
            model: OpenAI model to use (default: gpt-4.1-mini for speed)
        """
        self.model = os.getenv("SCRIPT_WRITER_MODEL", model)
        self._agent: Optional[Agent] = None

    def initialize(self, custom_instructions: str = "") -> None:
        """
        Initialize the agent with tools.

        Args:
            custom_instructions: Additional context (e.g., current session state)
        """
        instructions = SCRIPT_WRITER_INSTRUCTIONS
        if custom_instructions:
            instructions = instructions + "\n\n" + custom_instructions

        self._agent = Agent(
            name="Script Writer",
            instructions=instructions,
            model=self.model,
            model_settings=ModelSettings(
                # No reasoning needed for script generation (gpt-4.1-mini)
            ),
            tools=[
                generate_script,
                modify_script,
                validate_script,
                list_techniques,
                recommend_technique,
                record_technique_outcome,
            ],
        )

    @property
    def agent(self) -> Agent:
        """Get the underlying Agent instance for handoffs."""
        if not self._agent:
            raise RuntimeError("ScriptWriterAgent not initialized. Call initialize() first.")
        return self._agent


def create_script_writer(custom_instructions: str = "") -> Agent:
    """
    Factory function to create and initialize a script writer agent.

    Args:
        custom_instructions: Additional context to append

    Returns:
        Initialized Agent instance ready for use
    """
    writer = ScriptWriterAgent()
    writer.initialize(custom_instructions=custom_instructions)
    return writer.agent


# Convenience alias matching the agents/__init__.py export
ScriptWriterAgent = ScriptWriterAgent


# For testing
if __name__ == "__main__":
    import asyncio
    from agents import Runner

    async def test():
        print("Testing ScriptWriterAgent...")
        print("-" * 60)

        agent = create_script_writer()

        # Test script generation
        result = await Runner.run(
            agent,
            "Generate a Blender script for a rising mushroom cloud explosion with bright orange flames"
        )

        print(f"Response: {result.final_output}")

    asyncio.run(test())
